# NumPy Practice Session

In [ ]:
# pip install numpy

In [1]:
# import this library in jupyter notebook
import numpy as np

## Creating an array using numpy

In [2]:
# 1-D array
food = np.array(["pakora", "samosa", "jalebi"])
food

array(['pakora', 'samosa', 'jalebi'], dtype='<U6')

In [3]:
price = np.array([250,300,400])
price

array([250, 300, 400])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
len(price)

3

In [8]:
price[2]

400

In [9]:
food[1]

'samosa'

In [10]:
price.mean()

316.6666666666667

In [13]:
# zeros method
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
# ones method
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [16]:
# empty method
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
# range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
# specific range
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
# specific range with a specific intervals
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

In [22]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [26]:
# line space
np.linspace(0,10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [28]:
# specify tour data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [29]:
np.ones(5, dtype=np.float64)

array([1., 1., 1., 1., 1.])

----

## Array Functions

In [45]:
a = np.array([2,4,5,8,9,55,1,4.5,0.1,12])
a

array([ 2. ,  4. ,  5. ,  8. ,  9. , 55. ,  1. ,  4.5,  0.1, 12. ])

In [46]:
# sortng an array
a.sort()
a

array([ 0.1,  1. ,  2. ,  4. ,  4.5,  5. ,  8. ,  9. , 12. , 55. ])

In [47]:
b = np.array([3,2.4,99,22,18.5,88])
b

array([ 3. ,  2.4, 99. , 22. , 18.5, 88. ])

In [48]:
# concatenate array
c = np.concatenate((a,b))
c

array([ 0.1,  1. ,  2. ,  4. ,  4.5,  5. ,  8. ,  9. , 12. , 55. ,  3. ,
        2.4, 99. , 22. , 18.5, 88. ])

In [49]:
c.sort()
c

array([ 0.1,  1. ,  2. ,  2.4,  3. ,  4. ,  4.5,  5. ,  8. ,  9. , 12. ,
       18.5, 22. , 55. , 88. , 99. ])

## Two dimentional array(2-D array)

In [50]:
a = np.array([[1,2,3,4,5], [6,7,8,9,10]])
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
b = np.array([[3,6,5,9,1], [1,3,5,8,2]])
b

array([[3, 6, 5, 9, 1],
       [1, 3, 5, 8, 2]])

In [56]:
# concatenate
c = np.concatenate((a,b), axis=0)
c

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 3,  6,  5,  9,  1],
       [ 1,  3,  5,  8,  2]])

In [57]:
 np.concatenate((a,b), axis=1)

array([[ 1,  2,  3,  4,  5,  3,  6,  5,  9,  1],
       [ 6,  7,  8,  9, 10,  1,  3,  5,  8,  2]])

In [66]:
a = np.array([[[1,2,3,4,5],
               [6,7,8,9,10]],
              [[11,12,13,14,15],
               [16,17,18,19,20]],
              [[21,22,23,24,25],
               [26,27,28,29,30]]])
a

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [59]:
# to find the number of dimensions
a.ndim

3

In [64]:
# to find the size of array (number of elements)
a.size

30

In [65]:
# to find shape of array
a.shape

(3, 2, 5)

In [63]:
type(a)

numpy.ndarray

In [61]:
b = np.array([[1,3,5,7,9],[2,4,6,8,10],[5,10,15,20,25]])
b

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10],
       [ 5, 10, 15, 20, 25]])

In [62]:
b.ndim

2

In [68]:
a = np.arange(9)  # 3*3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [69]:
# reshape
b = a.reshape(3,3)  # 3*# = 9
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [70]:
# reshape
np.reshape(a, newshape = (1,9), order = "C")

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [71]:
# convert 1D to 2D array
a= np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a.shape

(9,)

In [82]:
# row wise 2D conversion
r = a[np.newaxis, :]
r

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [76]:
b.shape

(1, 9)

In [77]:
b.ndim

2

In [81]:
# column wise 2D conversion
c = a[: , np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [78]:
b = a.reshape(3,3)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [88]:
a*5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [89]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [90]:
a/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [91]:
a-4

array([-3, -2, -1,  0,  1,  2,  3,  4,  5])

In [92]:
a.sum()

45

In [93]:
a.mean()

5.0

In [94]:
a.max()

9

In [95]:
a.min()

1