# Installing NumPy

In [ ]:
# pip install numpy

# How to import NumPy

In [40]:
import numpy as np

# One dimentional array (1-D array)

## Vector
- A vector is an array with a sigle dimension(there is no difference between row and column vectors)

In [7]:
import numpy as np
a = np.array([6,6,6,6,6])
a

array([6, 6, 6, 6, 6])

### The Numpy ndarray is used to represent both matrices and vectors

In [8]:
type(a)

numpy.ndarray

In [9]:
len(a)

5

In [12]:
a[2]

6

In [13]:
a[1:4]

array([6, 6, 6])

In [18]:
t = np.zeros(4)
t

array([0., 0., 0., 0.])

In [19]:
z = np.ones(5)
z

array([1., 1., 1., 1., 1.])

In [25]:
# create an empty array with 2 elements
c = np.empty(2)
c

array([7.75824095e-312, 5.39198933e+067])

In [27]:
# You can create an array with a range of elements:
d = np.arange(6)
d

array([0, 1, 2, 3, 4, 5])

In [28]:
# with specific range of elements
e = np.arange(2,12)
e

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
# And even an array that contains a range of evenly spaced intervals. To do this, you will specify the first number,
# last number, and the step size.
f = np.arange(2,15,2)
f

array([ 2,  4,  6,  8, 10, 12, 14])

In [30]:
# linerly spaced arrays
# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
g = np.linspace(0,18,num=6)  # give use 6 numbers
g

array([ 0. ,  3.6,  7.2, 10.8, 14.4, 18. ])

In [31]:
# specific data types in array
h = np.ones(6, dtype=np.int8)
h

array([1, 1, 1, 1, 1, 1], dtype=int8)

In [32]:
j = np.ones(8, dtype=np.float64)
j

array([1., 1., 1., 1., 1., 1., 1., 1.])

# Adding, removing, and sorting elements

In [46]:
a = np.array([2,4,1,3,7,5,9,6,8])
a

array([2, 4, 1, 3, 7, 5, 9, 6, 8])

In [48]:
# Sorting an element is simple with np.sort(). 
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [55]:
b = np.array([5, 6, 7, 8])
b

array([5, 6, 7, 8])

In [56]:
# You can concatenate them with np.concatenate().
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [57]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [58]:
y = np.array([[5, 6]])
y

array([[5, 6]])

In [63]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

# How do you know the shape and size of an array?

# Two dimentional array (2-D array)

## Matrix
- A matrix refers to an array with two dimensions.

In [11]:
# list of lists
b = np.array([[6,6,6],[6,6,6],[6,6,6]])
b

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

### The Numpy ndarray is used to represent both matrices and vectors

In [14]:
type(b)

numpy.ndarray

In [15]:
len(b)

3

In [17]:
b[1:3]

array([[6, 6, 6],
       [6, 6, 6]])

In [33]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
np.zeros((5,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [37]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

# Three dimentional array (3-D or higher array)
- For 3-D or higher dimentional arrays, the term **tensor** is also used.

## TensorFlow
- TensorFlow is a free and open source software library for machine learning and artifical intelligence.

In [39]:
# making and reshaping a 3-D array
i = np.arange(18).reshape(2,3,3)
i

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])